name: airbornegeo
channels:
  - conda-forge
  - pytorch
  - nodefaults
dependencies:
  - python=3.12
  # Required dependencies
  - numpy>=2.0.0
  - scipy>=1.13.0
  - matplotlib>=3.9.0
  - pandas>=2.3.0
  - scikit-learn>=1.5.0
  - ipython>=8.23.0
  - harmonica
  - geopandas
  - pygmt
  - shapely
  - tqdm
  - verde
  - plotly
  - seaborn
  - scooby
  # test
  - pytest>=6
  - pytest-cov>=3
  # dev
  - jupyterlab
  # docs
  - sphinx>=7.0
  - myst-parser>=0.13
  - sphinx-copybutton
  - sphinx-autodoc-typehints
  - sphinx-book-theme>=0.3
  - nbsphinx
  - nbconvert
  - sphinxcontrib-bibtex
  - shpinx_design
  - polartoolkit>=1.5
  - invert4geom
  # below packages need to be installed with pip (aren't available in conda-forge)
  # - pip
  # - pip:
  #     -
