name: Docs Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - closed
    branches:
      - "main"
  workflow_dispatch:

concurrency: preview-${{github.ref}}

env:
  # Many color libraries just need this variable to be set to any value.
  # Set it to 3 to support 8-bit color graphics (256 colors per channel)
  # for libraries that care about the value set.
  FORCE_COLOR: 3

jobs:
  preview:
    runs-on: ubuntu-latest
    # only run if from the same repository, not a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v6

      # Install Micromamba with conda-forge dependencies
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          post-cleanup: "all"
          cache-downloads: false
          # environment cache is persistent for one week.
          cache-environment-key:
            micromamba-environment-${{ steps.date.outputs.date }}

      - id: install_pandoc
        run: sudo apt-get install pandoc

      - name: Install package
        run: pip install --no-deps -e . sphinx-autobuild

      # Build the documentation
      - name: Build the documentation
        if: github.event.action != 'closed'
        run: sphinx-autobuild -n -T -b="html" docs -- docs/_build/html

      # Deploy the preview of the docs
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_build/html
          preview-branch: gh-pages
          # custom-url:
          umbrella-dir: pr-preview
          action: auto
          deploy-repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
