name: Docs Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - closed
    branches:
      - "main"
  workflow_dispatch:

concurrency: preview-${{github.ref}}

env:
  # Many color libraries just need this variable to be set to any value.
  # Set it to 3 to support 8-bit color graphics (256 colors per channel)
  # for libraries that care about the value set.
  FORCE_COLOR: 3

jobs:
  preview:
    runs-on: ubuntu-latest
    # only run if from the same repository, not a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.64.0
          cache: true
          environments: docs

      # Build the documentation
      - name: Build the documentation
        if: github.event.action != 'closed'
        run: pixi run docs_static

      # Deploy the preview of the docs
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_build/html
          preview-branch: gh-pages
          # custom-url:
          umbrella-dir: pr-preview
          action: auto
          deploy-repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: false
          disable_nojekyll: false
